### PR TITLE
feat: add minor argument

### PR DESCRIPTION
**Pull request by rcruzper**
I've added a new argument to bump minor version instead of patch.
I wanted to test the feature mocking github requests to have control on the test so I wrapped github dependency with an interface in order to test this feature.
These solution decouples the app code from the github library applying clean architecture practices, allowing the implementation of other repositories as BitBucket or GitLab in the future.

### CODE REVIEW

**Comment by ccojocar** [comment]
@rcruzper Please can you rebase this pull-request? Thanks!

**Comment by ccojocar** [comment]
@rcruzper Closing this for now. It seem a bit outdated. Please fell free to open another PR. Thanks!

**Comment by rcruzper** [comment]
hi @ccojocar , I already opened a new pr with the rebase: #46

**Pull request closed without merging**
